# define to look on this git repo
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-flux
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/ezratameno/k8s-flux