apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  path: flux/namespaces/
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-flux
  validation: client