apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-prometheus
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - grafana.k8s-infra.mydomain.com
    
    # secret that holds the certificate name
    secretName: grafana-demo
    
  rules:
  # TODO: needed to add entry in the /etc/hosts to point grafana.k8s-infra.mydomain.com to 127.0.01
  - host: grafana.k8s-infra.mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: prometheus-community-grafana
           port:
             number: 80
    # TODO: needed to add entry in the /etc/hosts to point prometheus.k8s-infra.mydomain.com to 127.0.01
  - host: prometheus.k8s-infra.mydomain.com
    http:
      paths:
      # TODO: add prometheus also
      - path: /
        pathType: Prefix
        backend:
          service:
           name: prometheus-community-kube-prometheus
           port:
             number: 9090
  